<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr William Kay">
<meta name="dcterms.date" content="2025-10-28">

<title>Practical 2 - Correlation analysis – BI1001 Biostatistics Practicals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1d4f84655f446305ac42a8f1abcf7405.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BI1001 Biostatistics Practicals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practical 1 - Basics of R.html"> 
<span class="menu-text">Practical 1 - Basics of R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practical 1 - Exploring data and graphing.html"> 
<span class="menu-text">Practical 1 - Exploring data and graphing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practical 2 - Experimental design.html"> 
<span class="menu-text">Practical 2 - Experimental design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Practical 2 - Correlation analysis.html" aria-current="page"> 
<span class="menu-text">Practical 2 - Correlation analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practical 4 - Group comparisons.html"> 
<span class="menu-text">Practical 4 - Group comparisons</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practical 5 - Analysing count data.html"> 
<span class="menu-text">Practical 5 - Analysing count data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Practical 2 - Correlation analysis</h1>
<p class="subtitle lead">Testing for association between two continuous variables</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr William Kay </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 28, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="learning-outcomes-los" class="level1">
<h1>Learning Outcomes (LOs)</h1>
<p>Here’s what you should know and be able to do after completing this practical:</p>
<ul>
<li><p>LO1: Plot the association between two continuous variables</p></li>
<li><p>LO2: Rank data</p></li>
<li><p>LO3: Spot outliers and determine whether to remove them or not</p></li>
<li><p>LO4: Check statistical test assumptions</p></li>
<li><p>LO5: Perform appropriate correlation analyses</p></li>
<li><p>LO6: Interpret the results from correlation analysis</p></li>
<li><p>LO7: Report the results in prose</p></li>
<li><p>LO8: Know what to do when assumptions aren’t met</p></li>
</ul>
</section>
<section id="tutorial" class="level1">
<h1>TUTORIAL</h1>
<section id="parametric-correlation-analysis---pearsons-correlation" class="level3">
<h3 class="anchored" data-anchor-id="parametric-correlation-analysis---pearsons-correlation">Parametric correlation analysis - Pearson’s correlation</h3>
<p>For this tutorial, let’s work with the Alzheimer’s dataset (including also BMI data)</p>
<p>Like last time we’re going to set a seed so that we all get the same data (and therefore the same correlation analysis!</p>
<p>Set the seed to “16” and create the Alzheimers data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">16</span>) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Alzheimers <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">neurons =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">20</span>, <span class="dv">5</span>), <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">30</span>, <span class="dv">5</span>)),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Asymptomatic"</span>,<span class="st">"Symptomatic"</span>), <span class="at">each =</span> <span class="dv">100</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sex =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"M"</span>, <span class="dv">50</span>), <span class="fu">rep</span>(<span class="st">"M"</span>, <span class="dv">50</span>), <span class="fu">rep</span>(<span class="st">"F"</span>, <span class="dv">50</span>), <span class="fu">rep</span>(<span class="st">"F"</span>, <span class="dv">50</span>)),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">age =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">200</span>, <span class="dv">70</span>, <span class="dv">5</span>), <span class="dv">0</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">BMI =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">22</span>, <span class="dv">1</span>), <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">21</span>, <span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="explore-the-data" class="level4">
<h4 class="anchored" data-anchor-id="explore-the-data">Explore the data</h4>
<p>Remember, exploring the data is always a critical step</p>
<p>Take a quick look and summarise:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Alzheimers) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "neurons" "group"   "sex"     "age"     "BMI"    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Alzheimers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   neurons        group sex age      BMI
1 22.38207 Asymptomatic   M  68 21.60350
2 19.37310 Asymptomatic   M  76 22.15924
3 25.48108 Asymptomatic   M  67 22.80087
4 12.77885 Asymptomatic   M  73 21.75576
5 25.73915 Asymptomatic   M  62 23.72602
6 17.65794 Asymptomatic   M  71 22.38629</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(Alzheimers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     neurons       group sex age      BMI
195 28.56378 Symptomatic   F  69 20.71530
196 33.65319 Symptomatic   F  71 19.89047
197 29.57632 Symptomatic   F  72 20.25048
198 33.83304 Symptomatic   F  70 21.78484
199 27.18775 Symptomatic   F  72 19.11942
200 31.62627 Symptomatic   F  71 20.55365</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Alzheimers) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   200 obs. of  5 variables:
 $ neurons: num  22.4 19.4 25.5 12.8 25.7 ...
 $ group  : chr  "Asymptomatic" "Asymptomatic" "Asymptomatic" "Asymptomatic" ...
 $ sex    : chr  "M" "M" "M" "M" ...
 $ age    : num  68 76 67 73 62 71 62 63 73 72 ...
 $ BMI    : num  21.6 22.2 22.8 21.8 23.7 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Alzheimers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    neurons          group               sex                 age      
 Min.   : 8.408   Length:200         Length:200         Min.   :56.0  
 1st Qu.:20.260   Class :character   Class :character   1st Qu.:67.0  
 Median :25.350   Mode  :character   Mode  :character   Median :71.0  
 Mean   :25.195                                         Mean   :70.5  
 3rd Qu.:29.736                                         3rd Qu.:74.0  
 Max.   :43.147                                         Max.   :86.0  
      BMI       
 Min.   :17.67  
 1st Qu.:20.92  
 Median :21.53  
 Mean   :21.52  
 3rd Qu.:22.22  
 Max.   :24.20  </code></pre>
</div>
</div>
</section>
<section id="define-a-research-question-and-hypotheses" class="level4">
<h4 class="anchored" data-anchor-id="define-a-research-question-and-hypotheses">Define a research question and hypotheses</h4>
<p>Let’s test whether neuron cell density is associated with BMI</p>
<p><strong>Research Question</strong>: Is neuron cell density (M/g) associated with BMI?</p>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><p><strong>Null Hypothesis (H0)</strong>: There is no correlation between neuron cell density with BMI.</p></li>
<li><p><strong>Alternate Hypothesis (H1)</strong>: There is correlation between neuron cell density with BMI.</p></li>
</ul>
<p>As part of good data exploration, we should plot this association:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Alzheimers<span class="sc">$</span>neurons <span class="sc">~</span> Alzheimers<span class="sc">$</span>BMI, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="check-statistical-test-assumptions" class="level4">
<h4 class="anchored" data-anchor-id="check-statistical-test-assumptions">Check statistical test assumptions</h4>
<p>For the Pearson’s correlation there are a few assumptions:</p>
<section id="assumption-1-variables-must-be-continuous---check-using-str" class="level5">
<h5 class="anchored" data-anchor-id="assumption-1-variables-must-be-continuous---check-using-str"><strong>Assumption 1</strong>: Variables must be continuous - check using <code>str()</code></h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Alzheimers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   200 obs. of  5 variables:
 $ neurons: num  22.4 19.4 25.5 12.8 25.7 ...
 $ group  : chr  "Asymptomatic" "Asymptomatic" "Asymptomatic" "Asymptomatic" ...
 $ sex    : chr  "M" "M" "M" "M" ...
 $ age    : num  68 76 67 73 62 71 62 63 73 72 ...
 $ BMI    : num  21.6 22.2 22.8 21.8 23.7 ...</code></pre>
</div>
</div>
</section>
<section id="assumption-2-variables-are-approximately-normally-distributed---check-using-hist-and-qqnorm" class="level5">
<h5 class="anchored" data-anchor-id="assumption-2-variables-are-approximately-normally-distributed---check-using-hist-and-qqnorm"><strong>Assumption 2</strong>: Variables are approximately normally distributed - check using <code>hist()</code> and <code>qqnorm()</code></h5>
<p><strong>IMPORTANT</strong>: We must check each variable separately. Let’s check neurons, then BMI:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Alzheimers<span class="sc">$</span>neurons, <span class="at">main =</span> <span class="st">"Histogram"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(Alzheimers<span class="sc">$</span>neurons); <span class="fu">qqline</span>(Alzheimers<span class="sc">$</span>neurons)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Alzheimers<span class="sc">$</span>BMI, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(Alzheimers<span class="sc">$</span>BMI); <span class="fu">qqline</span>(Alzheimers<span class="sc">$</span>BMI)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both look to be normally distributed</p>
</section>
<section id="assumption-3-there-should-be-a-linear-relationship-between-both-variables---check-by-plotting-the-association" class="level5">
<h5 class="anchored" data-anchor-id="assumption-3-there-should-be-a-linear-relationship-between-both-variables---check-by-plotting-the-association"><strong>Assumption 3</strong>: There should be a linear relationship between both variables - check by plotting the association:</h5>
<p>Let’s start by plotting the data.</p>
<p>Then, we can add a line to the plot using the <code>abline()</code> function</p>
<p>Specifically, the following <code>abline()</code> function adds a line of best fit to the model - technically its the result of a <strong>linear model</strong>, which is what the function <code>lm()</code> means. You will learn linear models next year:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Alzheimers<span class="sc">$</span>neurons <span class="sc">~</span> Alzheimers<span class="sc">$</span>BMI, <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(Alzheimers<span class="sc">$</span>neurons <span class="sc">~</span> Alzheimers<span class="sc">$</span>BMI), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There does appear to be a consistent, linear pattern (it looks to have a negative correlation).</p>
</section>
<section id="assumption-4-the-data-have-no-outliers---boxplots-are-good-for-this" class="level5">
<h5 class="anchored" data-anchor-id="assumption-4-the-data-have-no-outliers---boxplots-are-good-for-this"><strong>Assumption 4</strong>: The data have no outliers - boxplots are good for this:</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Alzheimers<span class="sc">$</span>neurons, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Alzheimers<span class="sc">$</span>BMI, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"BMI"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It looks like BMI may have some observations that at first glance could be considered outliers. Specifically there are two observations that the boxplot highlights as being particularly small, and one that is particularly high.</p>
<p>Let’s check what the values are for these observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot.stats</span>(Alzheimers<span class="sc">$</span>BMI)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 19.11942 20.91338 21.53465 22.22375 24.18724

$n
[1] 200

$conf
[1] 21.38825 21.68104

$out
[1] 24.19552 18.34943 17.67189</code></pre>
</div>
</div>
<p>This shows us a few things:</p>
<ul>
<li><p><code>$stats</code>: min, Q1 (25th percentile), median, Q3 (75th percentile), and max (excluding outliers)</p></li>
<li><p><code>$n</code>: The number of observations</p></li>
<li><p><code>$conf</code>: The 95% confidence interval for the median</p></li>
<li><p><code>$out</code>: The values identified as outliers</p></li>
</ul>
<p>So the apparent outliers have BMI values of 24.2, 18.3, and 17.7</p>
<p>Let’s check by looking at a reputable source if these are likely to be erroneous observations or are quite normal. For this we could look at the NHS: https://www.nhs.uk/common-health-questions/lifestyle/what-is-the-body-mass-index-bmi</p>
<p>It turns out both BMI scores of 18.5 to 24.9 are in an ideal range.</p>
<p>A BMI below 18.5 is classed as underweight; over 24.9 is overweight</p>
<p>Check the range of our BMI values:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(Alzheimers<span class="sc">$</span>BMI)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.67189 24.19552</code></pre>
</div>
</div>
<p>The BMI range in our data is 17.7 to 24.2.</p>
<p>We could also see our data using the <code>sort()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(Alzheimers<span class="sc">$</span>BMI)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 17.67189 18.34943 19.11942 19.16731 19.33414 19.37257 19.42116 19.50100
  [9] 19.56896 19.59081 19.59085 19.66764 19.80200 19.85171 19.89047 19.94201
 [17] 20.02146 20.17369 20.22869 20.24717 20.25048 20.25300 20.29701 20.30795
 [25] 20.32051 20.32704 20.37314 20.37337 20.38961 20.46170 20.48748 20.50217
 [33] 20.50950 20.54161 20.55365 20.57046 20.58704 20.60141 20.69807 20.70657
 [41] 20.71428 20.71530 20.73378 20.76268 20.79377 20.83256 20.88405 20.89914
 [49] 20.89928 20.90983 20.91692 20.92147 20.92533 20.93464 20.95714 20.96354
 [57] 20.97517 20.99155 20.99252 20.99691 21.02190 21.03213 21.03355 21.05735
 [65] 21.09033 21.11244 21.11993 21.13480 21.21388 21.22276 21.23151 21.23245
 [73] 21.26043 21.27942 21.27987 21.28813 21.30485 21.31201 21.31670 21.33172
 [81] 21.35282 21.35630 21.36583 21.37906 21.38748 21.39677 21.40043 21.41131
 [89] 21.41394 21.43066 21.44158 21.45158 21.45421 21.48238 21.48662 21.49657
 [97] 21.50554 21.51626 21.51825 21.53324 21.53605 21.55642 21.56101 21.57660
[105] 21.57795 21.60350 21.60593 21.60701 21.61239 21.62195 21.64255 21.65174
[113] 21.69397 21.71868 21.72934 21.73336 21.73928 21.74021 21.75576 21.77598
[121] 21.78484 21.79652 21.81550 21.83326 21.87435 21.87657 21.88659 21.89197
[129] 21.89995 21.90013 21.90523 21.91520 21.92094 21.93792 21.96182 21.96943
[137] 22.00567 22.01945 22.07131 22.07240 22.08535 22.10125 22.11903 22.13829
[145] 22.14056 22.14749 22.15924 22.16502 22.20088 22.21320 22.23429 22.24819
[153] 22.26313 22.26764 22.27020 22.27753 22.30544 22.33494 22.34020 22.34316
[161] 22.38629 22.39333 22.41635 22.41915 22.45085 22.46061 22.50310 22.51687
[169] 22.54330 22.57838 22.58854 22.59163 22.59838 22.67519 22.68894 22.69780
[177] 22.80087 22.82222 22.82945 22.88112 22.90096 22.90871 22.93004 22.95975
[185] 22.98538 23.00929 23.12756 23.15591 23.21402 23.21550 23.30173 23.30968
[193] 23.32032 23.42368 23.67229 23.72602 23.83256 23.86702 24.18724 24.19552</code></pre>
</div>
</div>
<p>The two smallest observations (17.7 and 18.3) would be considered mildly anorexic: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8837073</p>
<p>Let’s check which those observations are using the <code>which()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(Alzheimers<span class="sc">$</span>BMI <span class="sc">&lt;</span> <span class="fl">18.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 139 185</code></pre>
</div>
</div>
<p>These observations exist on rows 139 and 185:</p>
<p>We could have a look at them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>Alzheimers[<span class="fu">c</span>(<span class="dv">139</span>, <span class="dv">185</span>), ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     neurons       group sex age      BMI
139 28.83582 Symptomatic   F  80 18.34943
185 30.70824 Symptomatic   F  77 17.67189</code></pre>
</div>
</div>
<p>Depending on the research question we were asking, these could be considered outliers:</p>
<p>If we wanted to only examine patients with “healthy” BMI scores, we may wish to exclude these.</p>
<p>Let’s assume we want to do that (let’s create a new subset with only healthy-BMI individuals):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>subAlz <span class="ot">&lt;-</span> Alzheimers[Alzheimers<span class="sc">$</span>BMI <span class="sc">&gt;</span> <span class="fl">18.5</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Technically we now need to check that our assumptions still hold with this subset, so let’s repeat our checks for assumptions 1-4:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(subAlz) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   198 obs. of  5 variables:
 $ neurons: num  22.4 19.4 25.5 12.8 25.7 ...
 $ group  : chr  "Asymptomatic" "Asymptomatic" "Asymptomatic" "Asymptomatic" ...
 $ sex    : chr  "M" "M" "M" "M" ...
 $ age    : num  68 76 67 73 62 71 62 63 73 72 ...
 $ BMI    : num  21.6 22.2 22.8 21.8 23.7 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(subAlz<span class="sc">$</span>neurons, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(subAlz<span class="sc">$</span>neurons); <span class="fu">qqline</span>(subAlz<span class="sc">$</span>neurons)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(subAlz<span class="sc">$</span>BMI, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>) </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(subAlz<span class="sc">$</span>BMI); <span class="fu">qqline</span>(subAlz<span class="sc">$</span>BMI) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(subAlz<span class="sc">$</span>neurons <span class="sc">~</span> subAlz<span class="sc">$</span>BMI, <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>) </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(subAlz<span class="sc">$</span>neurons <span class="sc">~</span> subAlz<span class="sc">$</span>BMI), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(subAlz<span class="sc">$</span>neurons, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(subAlz<span class="sc">$</span>BMI, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"BMI"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-14-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All assumptions 1-4 are met</p>
<p>Let’s look at the final assumption:</p>
</section>
<section id="assumption-5-your-data-must-be-independent-no-one-observation-affects-another" class="level5">
<h5 class="anchored" data-anchor-id="assumption-5-your-data-must-be-independent-no-one-observation-affects-another"><strong>Assumption 5</strong>: Your data must be independent (no one observation affects another)</h5>
<p>We don’t need to do anything in R to check this assumption - we just need to know how the data were collected. In this case the data is simulated so we can <strong>pretend</strong> that each observation comes from a unique individual, and no individual was sampled more than once, hence our observations are entirely independent from one another. There is no <strong>within-subject dependence</strong>.</p>
</section>
</section>
</section>
<section id="perform-the-correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="perform-the-correlation-analysis">Perform the correlation analysis</h2>
<p>As you can see - there is a lot of work in checking the assumptions are met before we perform a statistical test!</p>
<p>The reason this is so important is because if those assumptions are violated, the statistical test wont give you reliable results, and so you need to use a different test.</p>
<p>We have checked all the assumptions of a Pearson’s correlation are satisfied, so we can use this.</p>
<p>Let’s plot the data again so we can look at it alongside the output of the statistical test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(subAlz<span class="sc">$</span>neurons <span class="sc">~</span> subAlz<span class="sc">$</span>BMI, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Neuron cell density (m/g)"</span>, <span class="at">xlab =</span> <span class="st">"BMI"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(subAlz<span class="sc">$</span>neurons <span class="sc">~</span> subAlz<span class="sc">$</span>BMI), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(subAlz<span class="sc">$</span>neurons, subAlz<span class="sc">$</span>BMI, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  subAlz$neurons and subAlz$BMI
t = -4.1877, df = 196, p-value = 4.255e-05
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.4096494 -0.1532608
sample estimates:
       cor 
-0.2865778 </code></pre>
</div>
</div>
<section id="interpret-the-output" class="level3">
<h3 class="anchored" data-anchor-id="interpret-the-output">Interpret the output</h3>
<p>The results from the Pearson’s correlation demonstrated a weak, negative correlation between Neuron cell density (million/gram) and BMI (r = -0.29 (95% CI: -0.41 to -0.15), t = -4.19, df = 196, p = 4.23e-5).</p>
</section>
<section id="non-parametric-analysis-spearmans-correlation" class="level3">
<h3 class="anchored" data-anchor-id="non-parametric-analysis-spearmans-correlation">Non-Parametric Analysis: Spearman’s correlation</h3>
<p>For this we will use the RespiratoryFlow data (from Practical Session 1)</p>
<p>To import the data into R, we can use the <code>read.csv()</code> function, along with the <code>file.choose()</code> function:</p>
<p><strong>NOTE</strong>: This will open a new window on your device - navigate to the dataset that you have downloaded and select it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>flowData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.choose</span>(), <span class="at">header =</span> T, <span class="at">na.strings =</span> <span class="st">""</span>, <span class="at">stringsAsFactors =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="check-the-data" class="level2">
<h2 class="anchored" data-anchor-id="check-the-data">check the data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(flowData) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "student" "height"  "weight"  "age"     "gender" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flowData) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  student height weight age gender
1       1    163   63.4  20      F
2       2    173   66.9  18      F
3       3    168   65.0  18      F
4       4    169   82.0  18      F
5       5    162   59.0  18      F
6       6    172   68.0  19      F</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(flowData) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    student height weight age gender
206     206    174   64.2  18      M
207     207    176   61.9  19   &lt;NA&gt;
208     208    165     NA  NA   &lt;NA&gt;
209     209    176   75.0  19   &lt;NA&gt;
210     210    173   56.0  21   &lt;NA&gt;
211     211    167   60.0  21   &lt;NA&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(flowData) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   211 obs. of  5 variables:
 $ student: int  1 2 3 4 5 6 7 8 9 10 ...
 $ height : num  163 173 168 169 162 172 159 161 171 172 ...
 $ weight : num  63.4 66.9 65 82 59 68 52 51.6 64.8 68 ...
 $ age    : int  20 18 18 18 18 19 18 20 19 18 ...
 $ gender : Factor w/ 2 levels "F","M": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flowData)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    student          height          weight            age        gender   
 Min.   :  1.0   Min.   :147.0   Min.   : 37.20   Min.   :17.0   F   :126  
 1st Qu.: 53.5   1st Qu.:167.0   1st Qu.: 58.92   1st Qu.:18.0   M   : 80  
 Median :106.0   Median :173.0   Median : 65.20   Median :18.0   NA's:  5  
 Mean   :106.0   Mean   :173.1   Mean   : 68.16   Mean   :18.8             
 3rd Qu.:158.5   3rd Qu.:179.0   3rd Qu.: 75.00   3rd Qu.:19.0             
 Max.   :211.0   Max.   :210.0   Max.   :178.00   Max.   :28.0             
                                 NA's   :1        NA's   :1                </code></pre>
</div>
</div>
</section>
<section id="data-exploration" class="level2">
<h2 class="anchored" data-anchor-id="data-exploration">Data exploration</h2>
<p>Let’s start by assessing a simple association</p>
<p><strong>Research Question</strong>: Is weight (kg) associated with height (cm)?</p>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><p><strong>Null Hypothesis (H0):</strong> There is no correlation between weight and height.</p></li>
<li><p><strong>Alternate Hypothesis (H1):</strong> There is a correlation between weight and height.</p></li>
</ul>
<p>We should start by plotting the association:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flowData<span class="sc">$</span>weight <span class="sc">~</span> flowData<span class="sc">$</span>height, <span class="at">ylab =</span> <span class="st">"Height (cm)"</span>, <span class="at">xlab =</span> <span class="st">"Weight (kg)"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="check-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-assumptions">Check assumptions</h2>
<section id="assumption-1-both-variables-must-be-continuous-numeric---check-using-str" class="level5">
<h5 class="anchored" data-anchor-id="assumption-1-both-variables-must-be-continuous-numeric---check-using-str">Assumption 1: Both variables must be continuous (numeric) - check using <code>str()</code></h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(flowData)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   211 obs. of  5 variables:
 $ student: int  1 2 3 4 5 6 7 8 9 10 ...
 $ height : num  163 173 168 169 162 172 159 161 171 172 ...
 $ weight : num  63.4 66.9 65 82 59 68 52 51.6 64.8 68 ...
 $ age    : int  20 18 18 18 18 19 18 20 19 18 ...
 $ gender : Factor w/ 2 levels "F","M": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
</section>
<section id="assumption-2-both-variables-are-approximately-normal---check-using-hist-qqnorm" class="level5">
<h5 class="anchored" data-anchor-id="assumption-2-both-variables-are-approximately-normal---check-using-hist-qqnorm">Assumption 2: Both variables are approximately normal - check using <code>hist()</code>, <code>qqnorm()</code></h5>
<p>Check height:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(flowData<span class="sc">$</span>height, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(flowData<span class="sc">$</span>height); <span class="fu">qqline</span>(flowData<span class="sc">$</span>height)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looks like the largest value of height is ~ 2.1 m tall - this is unlikely to be an error or outlier but rather just a particularly tall person (e.g., a basketball player!)</p>
<p>Let’s check weight:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(flowData<span class="sc">$</span>weight, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(flowData<span class="sc">$</span>weight); <span class="fu">qqline</span>(flowData<span class="sc">$</span>weight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Definitely does not look normal.</p>
<p>In fact, as well as the distribution looking skewed, it looks like there is an outlier - someone is ~180 kg (28.3 stone).</p>
</section>
<section id="assumption-3-there-should-be-a-linear-relationship-between-both-variables---check-using-plot" class="level5">
<h5 class="anchored" data-anchor-id="assumption-3-there-should-be-a-linear-relationship-between-both-variables---check-using-plot">Assumption 3: There should be a linear relationship between both variables - check using <code>plot()</code></h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flowData<span class="sc">$</span>weight <span class="sc">~</span> flowData<span class="sc">$</span>height, </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Weight (kg)"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>, <span class="at">las =</span> <span class="dv">1</span>) </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(flowData<span class="sc">$</span>weight <span class="sc">~</span> flowData<span class="sc">$</span>height), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assumption-4-the-data-have-no-outliers---check-using-boxplot" class="level5">
<h5 class="anchored" data-anchor-id="assumption-4-the-data-have-no-outliers---check-using-boxplot">Assumption 4: The data have no outliers - check using boxplot()</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(flowData<span class="sc">$</span>height)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(flowData<span class="sc">$</span>weight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There certainly appear to be some outliers!</p>
</section>
<section id="assumption-5-your-data-must-be-independent-no-one-observation-affects-another-1" class="level5">
<h5 class="anchored" data-anchor-id="assumption-5-your-data-must-be-independent-no-one-observation-affects-another-1">Assumption 5: Your data must be independent (no one observation affects another)</h5>
<p>We know that these data are independent, because all the observations come from different people, so this assumption is satisfied.</p>
</section>
</section>
<section id="run-an-appropriate-correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="run-an-appropriate-correlation-analysis">Run an appropriate correlation analysis</h2>
<p>We have checked the assumptions of a Pearson’s correlation and failed to satisfy the assumptions of normality and outliers.</p>
<p>We would in theory have some other options to explore before ruling out parametric analysis altogether. For example, we could consider whether removal of outliers would be appropriate and we could consider <strong>transforming</strong> the weight variable using something like <code>log()</code> to see if the log(weight) is normally distributed. We will explore those ideas later.</p>
<p>For now, let’s assume we can’t meet the assumptions of a parametric (Pearson’s) correlation</p>
<p>Hence, we need to run a Non-Parametric analysis (e.g., a Spearman’s rank correlation)</p>
</section>
<section id="spearmans-rank-correlation" class="level2">
<h2 class="anchored" data-anchor-id="spearmans-rank-correlation">Spearman’s rank correlation</h2>
<p>Spearman’s rank analysis looks at the <strong>ranks</strong> of the observations, rather than the raw values themselves.</p>
<p>In fact, variables being <strong>ranked</strong> is the 1st assumption of the Spearman’s rank correlation</p>
<p>To understand ranks, let’s first look at the raw data, e.g., for the height variable</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>flowData<span class="sc">$</span>height</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 163.0 173.0 168.0 169.0 162.0 172.0 159.0 161.0 171.0 172.0 184.0 160.0
 [13] 160.0 158.0 169.0 150.0 164.0 175.0 174.0 166.0 157.0 174.0 178.0 180.0
 [25] 169.0 177.0 167.0 169.0 172.0 168.0 163.0 164.0 158.0 172.0 178.0 167.0
 [37] 159.0 171.0 172.0 167.0 172.0 171.0 162.0 177.0 167.0 179.0 174.0 174.0
 [49] 174.0 179.0 164.0 175.0 163.0 170.0 164.0 147.0 165.0 174.0 158.0 168.0
 [61] 167.0 169.0 162.0 168.0 158.0 162.0 167.0 174.0 170.0 163.0 161.0 178.0
 [73] 174.0 164.0 176.0 173.0 171.0 170.0 163.0 168.0 160.0 174.0 165.0 176.5
 [85] 164.0 168.0 167.0 179.0 174.0 164.0 166.0 169.0 169.0 172.0 172.0 153.0
 [97] 183.0 179.0 170.0 176.0 171.0 165.0 158.0 166.0 162.0 147.0 171.0 168.0
[109] 165.0 172.0 164.0 171.0 177.0 161.0 163.0 172.0 160.0 162.0 180.0 179.0
[121] 166.0 168.0 170.0 160.0 155.0 171.0 167.0 180.0 182.0 193.0 189.0 178.0
[133] 193.0 174.0 178.0 176.0 188.0 188.0 186.0 210.0 184.0 179.0 186.0 184.0
[145] 169.0 181.0 178.0 177.0 191.0 177.0 183.0 175.0 181.0 190.0 200.0 189.0
[157] 180.0 191.0 185.0 186.0 168.0 180.0 172.5 181.0 173.5 175.0 180.0 180.0
[169] 183.0 196.0 180.0 176.0 187.0 176.0 178.5 177.0 169.0 180.0 176.0 179.0
[181] 181.0 178.0 174.0 176.0 185.0 190.0 177.0 189.0 186.0 181.0 183.0 184.0
[193] 182.0 185.0 173.0 181.0 176.0 187.0 186.0 171.0 169.0 185.0 163.0 179.0
[205] 190.0 174.0 176.0 165.0 176.0 173.0 167.0</code></pre>
</div>
</div>
<p>In fact it may be easier to look at these values when they are sorted from smallest to largest:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(flowData<span class="sc">$</span>height)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 147.0 147.0 150.0 153.0 155.0 157.0 158.0 158.0 158.0 158.0 158.0 159.0
 [13] 159.0 160.0 160.0 160.0 160.0 160.0 161.0 161.0 161.0 162.0 162.0 162.0
 [25] 162.0 162.0 162.0 163.0 163.0 163.0 163.0 163.0 163.0 163.0 164.0 164.0
 [37] 164.0 164.0 164.0 164.0 164.0 164.0 165.0 165.0 165.0 165.0 165.0 166.0
 [49] 166.0 166.0 166.0 167.0 167.0 167.0 167.0 167.0 167.0 167.0 167.0 167.0
 [61] 168.0 168.0 168.0 168.0 168.0 168.0 168.0 168.0 168.0 169.0 169.0 169.0
 [73] 169.0 169.0 169.0 169.0 169.0 169.0 169.0 170.0 170.0 170.0 170.0 170.0
 [85] 171.0 171.0 171.0 171.0 171.0 171.0 171.0 171.0 171.0 172.0 172.0 172.0
 [97] 172.0 172.0 172.0 172.0 172.0 172.0 172.0 172.5 173.0 173.0 173.0 173.0
[109] 173.5 174.0 174.0 174.0 174.0 174.0 174.0 174.0 174.0 174.0 174.0 174.0
[121] 174.0 174.0 175.0 175.0 175.0 175.0 176.0 176.0 176.0 176.0 176.0 176.0
[133] 176.0 176.0 176.0 176.0 176.5 177.0 177.0 177.0 177.0 177.0 177.0 177.0
[145] 178.0 178.0 178.0 178.0 178.0 178.0 178.0 178.5 179.0 179.0 179.0 179.0
[157] 179.0 179.0 179.0 179.0 180.0 180.0 180.0 180.0 180.0 180.0 180.0 180.0
[169] 180.0 181.0 181.0 181.0 181.0 181.0 181.0 182.0 182.0 183.0 183.0 183.0
[181] 183.0 184.0 184.0 184.0 184.0 185.0 185.0 185.0 185.0 186.0 186.0 186.0
[193] 186.0 186.0 187.0 187.0 188.0 188.0 189.0 189.0 189.0 190.0 190.0 190.0
[205] 191.0 191.0 193.0 193.0 196.0 200.0 210.0</code></pre>
</div>
</div>
<p>So we can see that the shortest person is 147.0 cm (and note that there are two people of this height). The tallest person is 210.0 cm.</p>
<p>Let’s now look at the ranks of these observations:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rank</span>(<span class="fu">sort</span>(flowData<span class="sc">$</span>height))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   1.5   1.5   3.0   4.0   5.0   6.0   9.0   9.0   9.0   9.0   9.0  12.5
 [13]  12.5  16.0  16.0  16.0  16.0  16.0  20.0  20.0  20.0  24.5  24.5  24.5
 [25]  24.5  24.5  24.5  31.0  31.0  31.0  31.0  31.0  31.0  31.0  38.5  38.5
 [37]  38.5  38.5  38.5  38.5  38.5  38.5  45.0  45.0  45.0  45.0  45.0  49.5
 [49]  49.5  49.5  49.5  56.0  56.0  56.0  56.0  56.0  56.0  56.0  56.0  56.0
 [61]  65.0  65.0  65.0  65.0  65.0  65.0  65.0  65.0  65.0  74.5  74.5  74.5
 [73]  74.5  74.5  74.5  74.5  74.5  74.5  74.5  82.0  82.0  82.0  82.0  82.0
 [85]  89.0  89.0  89.0  89.0  89.0  89.0  89.0  89.0  89.0  98.5  98.5  98.5
 [97]  98.5  98.5  98.5  98.5  98.5  98.5  98.5 104.0 106.5 106.5 106.5 106.5
[109] 109.0 116.0 116.0 116.0 116.0 116.0 116.0 116.0 116.0 116.0 116.0 116.0
[121] 116.0 116.0 124.5 124.5 124.5 124.5 131.5 131.5 131.5 131.5 131.5 131.5
[133] 131.5 131.5 131.5 131.5 137.0 141.0 141.0 141.0 141.0 141.0 141.0 141.0
[145] 148.0 148.0 148.0 148.0 148.0 148.0 148.0 152.0 156.5 156.5 156.5 156.5
[157] 156.5 156.5 156.5 156.5 165.0 165.0 165.0 165.0 165.0 165.0 165.0 165.0
[169] 165.0 172.5 172.5 172.5 172.5 172.5 172.5 176.5 176.5 179.5 179.5 179.5
[181] 179.5 183.5 183.5 183.5 183.5 187.5 187.5 187.5 187.5 192.0 192.0 192.0
[193] 192.0 192.0 195.5 195.5 197.5 197.5 200.0 200.0 200.0 203.0 203.0 203.0
[205] 205.5 205.5 207.5 207.5 209.0 210.0 211.0</code></pre>
</div>
</div>
<p>We see that the observations are now ranked from smallest to largest. Importantly, because there are two values of the smallest height, rather than these be ranked “1” and “2”, they have a shared rank of 1.5. This is known as a <strong>tie</strong> in the ranks.</p>
<p>We can look at both the actual value of height and the rank together using <code>cbind()</code> (column bind):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>both <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">sort</span>(flowData<span class="sc">$</span>height), <span class="fu">rank</span>(<span class="fu">sort</span>(flowData<span class="sc">$</span>height)))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(both, <span class="dv">10</span>) <span class="co"># Note the 10 here tells R to show me the first 10 rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2]
 [1,]  147  1.5
 [2,]  147  1.5
 [3,]  150  3.0
 [4,]  153  4.0
 [5,]  155  5.0
 [6,]  157  6.0
 [7,]  158  9.0
 [8,]  158  9.0
 [9,]  158  9.0
[10,]  158  9.0</code></pre>
</div>
</div>
<p>To exemplify this further to ensure you understand, let’s look at a very small example:</p>
<p>Imagine we had the actual observations of 1, 4, 10, 10, 15, and 20.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If we rank these, we see that 1 is the smallest rank (1) and 20 is the highest (6). 10 occurs twice so rather than the first 10 get a rank of 3 and the second 10 get a rank of 4, these two 10s share the rank of 3.5:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>obs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  4 10 10 15 20</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rank</span>(obs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0 2.0 3.5 3.5 5.0 6.0</code></pre>
</div>
</div>
<p>As well as the data needing to be ranked, the Spearman’s correlation has two other assumptions:</p>
<section id="observations-are-independent" class="level5">
<h5 class="anchored" data-anchor-id="observations-are-independent">2. Observations are independent</h5>
<p>We already know that this is the case - all data come from different individuals</p>
<section id="relationship-between-variables-is-monotonic" class="level6">
<h6 class="anchored" data-anchor-id="relationship-between-variables-is-monotonic">3. Relationship between variables is monotonic</h6>
<p>This means that monotonic relationship means that as one variable increases, the other always tends to go in a consistent direction (always up, or always down)</p>
<p>We can see this when we plot the data, and importantly note that this assumption is about the raw data, not the ranked data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flowData<span class="sc">$</span>weight <span class="sc">~</span> flowData<span class="sc">$</span>height, </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Weight (kg)"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>, <span class="at">las =</span> <span class="dv">1</span>) </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(flowData<span class="sc">$</span>weight <span class="sc">~</span> flowData<span class="sc">$</span>height), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>So, we are confident that the assumptions for a Spearman’s rank correlation analysis are met</p>
<p>Let’s now visualise this potential association and perform the analysis</p>
<p>Remember we need to visualise the association <strong>between the ranks</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rank</span>(flowData<span class="sc">$</span>weight), <span class="fu">rank</span>(flowData<span class="sc">$</span>height), <span class="at">ylab =</span> <span class="st">"Weight (kg)"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>, <span class="at">las =</span> <span class="dv">1</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(<span class="fu">rank</span>(flowData<span class="sc">$</span>weight) <span class="sc">~</span> <span class="fu">rank</span>(flowData<span class="sc">$</span>height)), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>IMPORTANT</strong>: When we perform the correlation analysis in R, we do not need to manually rank the variables i.e.&nbsp;we do not need to write for example <code>rank(flowData$weight)</code></p>
<p>This is because when we specify <code>method = "spearman"</code> in the <code>cor.test()</code> function, this tells R to rank the variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(flowData<span class="sc">$</span>weight, flowData<span class="sc">$</span>height, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(flowData$weight, flowData$height, method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  flowData$weight and flowData$height
S = 501622, p-value &lt; 2.2e-16
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.6750029 </code></pre>
</div>
</div>
<p>The warning of ties simply tells us that there are several observations which share the same rank (we knew this already)</p>
<p>In fact, when there are many ties, it’s better to use the Kendall’s tau correlation.</p>
<p>Kendall’s tau correlation also examines the association between ranks, and it is slightly more robust with small sample sizes or tied ranks. Kendall’s tau correlation has <strong>the same assumptions as Spearman’s</strong>, so we don’t need to check those all over again!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(flowData<span class="sc">$</span>weight, flowData<span class="sc">$</span>height, <span class="at">method =</span> <span class="st">"kendall"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kendall's rank correlation tau

data:  flowData$weight and flowData$height
z = 10.573, p-value &lt; 2.2e-16
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.4992785 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="interpret-the-output-1" class="level2">
<h2 class="anchored" data-anchor-id="interpret-the-output-1">Interpret the output</h2>
<p>The results from the Kendall’s tau correlation demonstrated a moderate, positive correlation between weight (kg) and height (cm) (tau = 0.5, z = 10.57, n = 210, p &lt; 2.2e-16).</p>
<section id="alternative-approaches-when-parametric-assumptions-are-violated" class="level3">
<h3 class="anchored" data-anchor-id="alternative-approaches-when-parametric-assumptions-are-violated">Alternative approaches when parametric assumptions are violated:</h3>
<p>I mentioned earlier that rather than immediately having to use a non-parametric test when parametric assumptions are violated, we may actually have other options.</p>
<p>In the <code>flowData</code> example above, the assumptions of normality and outliers were violated.</p>
<p>Let’s see if we can address those.</p>
<p>Depending on your research question, it may be appropriate to remove the outlier in weight:</p>
<p>Remember this was the observation of ~ 180 kg:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(flowData<span class="sc">$</span>weight, <span class="at">las =</span> <span class="dv">1</span>, <span class="at">ylab =</span> <span class="st">"Weight (kg)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We could create a subset that retains only individuals whose weight is less than 120 kg:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>flowSub <span class="ot">&lt;-</span> <span class="fu">subset</span>(flowData, flowData<span class="sc">$</span>weight <span class="sc">&lt;</span> <span class="dv">120</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s now plot the association:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flowSub<span class="sc">$</span>weight <span class="sc">~</span> flowSub<span class="sc">$</span>height, <span class="at">las =</span> <span class="dv">1</span>, </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Weight (kg)"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It no longer looks like there are any obvious outliers.</p>
<p>What about normality?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(flowSub<span class="sc">$</span>height, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(flowSub<span class="sc">$</span>height); <span class="fu">qqline</span>(flowSub<span class="sc">$</span>height)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(flowSub<span class="sc">$</span>weight, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"Weight (kg)"</span>)</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(flowSub<span class="sc">$</span>weight); <span class="fu">qqline</span>(flowSub<span class="sc">$</span>weight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Even with the outlier removed, the weight data still looks like it doesn’t follow a normal distribution. So, let’s see if we can transform the data:</p>
<p>Let’s try taking the log of weight:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>flowSub<span class="sc">$</span>logWt <span class="ot">&lt;-</span> <span class="fu">log</span>(flowSub<span class="sc">$</span>weight) </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(flowSub<span class="sc">$</span>logWt, <span class="at">main =</span> <span class="st">"Histogram"</span>, <span class="at">xlab =</span> <span class="st">"log Weight (kg)"</span>)</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(flowSub<span class="sc">$</span>logWt); <span class="fu">qqline</span>(flowSub<span class="sc">$</span>logWt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This now looks much more like it follows a normal distribution!</p>
<p>Now, all assumptions are satisfied to perform a more powerful, parametric test.</p>
<p>Let’s plot the data, and perform the test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flowSub<span class="sc">$</span>logWt <span class="sc">~</span> flowSub<span class="sc">$</span>height, <span class="at">ylab =</span> <span class="st">"log Weight (kg)"</span>, <span class="at">xlab =</span> <span class="st">"Height (cm)"</span>, <span class="at">las =</span> <span class="dv">1</span>) </span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(flowSub<span class="sc">$</span>logWt <span class="sc">~</span> flowSub<span class="sc">$</span>height), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical-2---Correlation-analysis_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(flowSub<span class="sc">$</span>logWt, flowSub<span class="sc">$</span>height, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  flowSub$logWt and flowSub$height
t = 14.017, df = 207, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6209031 0.7614210
sample estimates:
      cor 
0.6978158 </code></pre>
</div>
</div>
<p>Whatever you decide to do - you just need to be transparent and provide appropriate justification for the decisions you make!</p>
</section>
</section>
<section id="interpreting-this-output" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-this-output">Interpreting this output:</h2>
<p>Note that now our result represents the association between height and the log of weight. Hence when we come to write up our results we have to be clear about that:</p>
<p>The results from the Pearson’s correlation demonstrated a strong, positive correlation between height (cm) and the log of weight (kg) (r = 0.70 (95% CI: 0.62 to 0.76), t = 14.02, df = 207, p &lt; 2.2e-16).</p>
</section>
</section>
<section id="tasks" class="level1">
<h1>TASKS</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write up the result for the Pearson’s correlation between log Weight and Height:</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Run the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>) </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>storks <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">8</span>, <span class="dv">1</span>), <span class="dv">0</span>) </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>babies <span class="ot">&lt;-</span> <span class="fu">round</span>(((<span class="dv">3</span> <span class="sc">*</span> storks) <span class="sc">+</span> <span class="dv">10</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now write the code to perform an <strong>appropriate</strong> correlation analysis to examine if there is an association between storks and babies.</p>
<p>Remember to explore the data thoroughly and check any assumptions are met</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write up the results for your correlation analysis of storks and babies</p>
</div>
</div>
</div>
</section>
<section id="bonus" class="level1">
<h1>Bonus:</h1>
<p>Note that for some analyses R can actually write up results in prose for you!</p>
<p>For example, the <code>report</code> package provides functions to report statistical tests.</p>
<p>Specifically, the <code>report()</code> function can be used to report correlation analyses:</p>
<p>Install and load the package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"report"</span>, <span class="at">repos =</span> <span class="st">"https://cloud.r-project.org/"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/sbiwk/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>package 'report' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\sbiwk\AppData\Local\Temp\Rtmpmk1CV7\downloaded_packages</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'report' was built under R version 4.5.1</code></pre>
</div>
</div>
<p>Perform the correlation test and save the output of the test in an object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>cor_result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(flowSub<span class="sc">$</span>logWt, flowSub<span class="sc">$</span>height, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Use <code>report()</code> to get R to report the correlation for you!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(cor_result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Funder's (2019) recommendations.

The Pearson's product-moment correlation between flowSub$logWt and
flowSub$height is positive, statistically significant, and very large (r =
0.70, 95% CI [0.62, 0.76], t(207) = 14.02, p &lt; .001)</code></pre>
</div>
</div>
<p><strong>IMPORTANT</strong>: You must always check that this has written something sensible! Do not simply rely on this output without checking!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>